In [2]:
import mayavi.mlab as mlab
from numpy import *
import numpy as np


In [16]:
mlab.test_contour3d()
mlab.show()

In [3]:
t = linspace(0,2*pi,50)
u = cos(t)*pi
x,y,z = sin(u),cos(u),sin(t)
mlab.points3d(x,y,z,t,colormap = 'Reds',scale_mode='none')
mlab.show()

In [1]:
x, y = np.mgrid[-10:10:100j, -10:10:100j]
r = np.sqrt(x**2 + y**2)
z = np.sin(r)/r
print(z)
#mlab.surf(z, warp_scale='auto')
#mlab.show()

NameError: name 'np' is not defined

In [4]:
t = linspace(0,2*pi,50)
u = cos(t)*pi
x,y,z = sin(u),cos(u),sin(t)
mlab.plot3d(x,y,z,t,colormap = 'Reds')
mlab.show()

In [5]:
z = linspace(0,2*pi,500)
u = 20
x,y = sin(u*z),cos(u*z)
mlab.plot3d(x,y,z,colormap = 'Reds')
mlab.show()

In [3]:
x,y = mgrid[-3:3:0.5,-3:3:100j]

print(x,y)
z = sin(x**2 + y**2)
mlab.surf(x,y,z)
mlab.show()

[[-3.  -3.  -3.  ... -3.  -3.  -3. ]
 [-2.5 -2.5 -2.5 ... -2.5 -2.5 -2.5]
 [-2.  -2.  -2.  ... -2.  -2.  -2. ]
 ...
 [ 1.5  1.5  1.5 ...  1.5  1.5  1.5]
 [ 2.   2.   2.  ...  2.   2.   2. ]
 [ 2.5  2.5  2.5 ...  2.5  2.5  2.5]] [[-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 ...
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]]


In [ ]:
x,y = mgrid[-3:3:100j,-3:3:100j]


z = sin(x*x + y*y)

mlab.contour_surf(x,y,z)
mlab.show()




In [ ]:
mlab.surf(x,y,z)
mlab.show()

In [11]:
mlab.mesh(x,y,z)
mlab.show()

In [14]:
phi,theta = mgrid[0:2*pi:200j,0:2*pi:200j]

u = 2
p = 4.1
x = sin(u*phi)*cos(p*theta)
y = sin(u*phi)*sin(p*theta)
z = cos(phi)

mlab.mesh(x,y,z)
#mlab.mesh(x,y,z,representation = 'wireframe')
mlab.show()


In [13]:
#triagular mesh
import numpy as np
x,y,z = [[0.,1.,1],[0.,0.,1],[0.,0,0]]
t = [[0,1,2],] 

points = np.array( [[0.,1.,1],[0.,0.,1],[0.,0,0]])
x,y,z = points.T

mlab.triangular_mesh(x,y,z,t)
mlab.show()

In [2]:
import mayavi.mlab as mlab
from numpy import *
import numpy as np


x , y = mgrid[-10:10:100j , -10:10:100j]
r = sqrt(x **2 + y **2)
s = mlab.mesh(x,y,sin(r)/r,extent=(0,1,0,1,0,1))
mlab.outline(s,extent=(0,1,0,1,0,1) )
mlab.axes(s,extent=(0,1,0,1,0,1))
mlab.show()

In [4]:
import mayavi.mlab as mlab
from numpy import *
import numpy as np
from EMFFeko import *
from matplotlib import pyplot as plt
import pandas as pd

ff1 = GetFarField('IEC-62232-panel-antenna (4)_FarField1.ffe')

theta, phi = mgrid[0:360:1j,0:360:1j]
print(theta)

ModuleNotFoundError: No module named 'EMFFeko'