In [3]:
import mayavi.mlab as mlab
from numpy import *
import numpy as np


In [5]:
t = linspace(0,2*pi,50)
u = cos(t)*pi
x,y,z = sin(u),cos(u),sin(t)
mlab.points3d(x,y,z,t,colormap = 'Reds',scale_mode='none')
mlab.show()

In [6]:
x, y = np.mgrid[-10:10:100j, -10:10:100j]
r = np.sqrt(x**2 + y**2)
z = np.sin(r)/r
print(z)
mlab.surf(r, warp_scale='auto')
mlab.show()

[[0.07070981 0.07075774 0.06938729 ... 0.06938729 0.07075774 0.07070981]
 [0.07075774 0.06934346 0.06649457 ... 0.06649457 0.06934346 0.07075774]
 [0.06938729 0.06649457 0.06217951 ... 0.06217951 0.06649457 0.06938729]
 ...
 [0.06938729 0.06649457 0.06217951 ... 0.06217951 0.06649457 0.06938729]
 [0.07075774 0.06934346 0.06649457 ... 0.06649457 0.06934346 0.07075774]
 [0.07070981 0.07075774 0.06938729 ... 0.06938729 0.07075774 0.07070981]]


In [7]:
t = linspace(0,2*pi,50)
u = cos(t)*pi
x,y,z = sin(u),cos(u),sin(t)
mlab.plot3d(x,y,z,t,colormap = 'Reds')
mlab.show()

In [8]:
z = linspace(0,2*pi,500)
u = 20
x,y = sin(u*z),cos(u*z)
mlab.plot3d(x,y,z,colormap = 'Reds')
mlab.show()

In [9]:
x,y = mgrid[-3:3:100j,-3:3:100j]

print(x,y)
z = sin(x**2 + y**2)
mlab.surf(x,y,z)
mlab.show()

[[-3.         -3.         -3.         ... -3.         -3.
  -3.        ]
 [-2.93939394 -2.93939394 -2.93939394 ... -2.93939394 -2.93939394
  -2.93939394]
 [-2.87878788 -2.87878788 -2.87878788 ... -2.87878788 -2.87878788
  -2.87878788]
 ...
 [ 2.87878788  2.87878788  2.87878788 ...  2.87878788  2.87878788
   2.87878788]
 [ 2.93939394  2.93939394  2.93939394 ...  2.93939394  2.93939394
   2.93939394]
 [ 3.          3.          3.         ...  3.          3.
   3.        ]] [[-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 ...
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]
 [-3.         -2.93939394 -2.87878788 ...  2.87878788  2.93939394
   3.        ]]


In [10]:
x,y = mgrid[-3:3:100j,-3:3:100j]


z = sin(x*x + y*y)

mlab.contour_surf(x,y,z)
mlab.show()




In [11]:
mlab.surf(x,y,z)
mlab.show()

In [12]:
mlab.mesh(x,y,z)
mlab.show()

In [13]:
phi,theta = mgrid[0:2*pi:200j,0:2*pi:200j]

u = 2
p = 4.1
x = sin(u*phi)*cos(p*theta)
y = sin(u*phi)*sin(p*theta)
z = cos(phi)

mlab.mesh(x,y,z)
#mlab.mesh(x,y,z,representation = 'wireframe')
mlab.show()


In [14]:
#triagular mesh
import numpy as np
x,y,z = [[0.,1.,1],[0.,0.,1],[0.,0,0]]
t = [[0,1,2],] 

points = np.array( [[0.,1.,1],[0.,0.,1],[0.,0,0]])
x,y,z = points.T

mlab.triangular_mesh(x,y,z,t)
mlab.show()

In [2]:
import mayavi.mlab as mlab
from numpy import *
import numpy as np
from EMFFeko import *
from matplotlib import pyplot as plt
import pandas as pd

ff1 = GetFarField('IEC-62232-panel-antenna_FarField1.ffe')
ff2 = GetFarField('test1.ffe')
print(ff2['Directivity(Total)'].max())
print(ff1['Directivity(Total)'].max())

#print(ff1['Directivity(Total)'])
phi, theta  = mgrid[0:361:1,0:181:1]
Gnum = 10**(ff2['Directivity(Total)'].to_numpy()/10)
lamda = 1/3
AF = 20*np.log10(9.73/(lamda*np.sqrt(Gnum)))
f = Gnum
f = np.reshape(f,(361,181))
x = f*np.sin(theta*np.pi/180)*np.cos(phi*np.pi/180)
y = f*np.sin(theta*np.pi/180)*np.sin(phi*np.pi/180)
z = f*np.cos(theta*np.pi/180)
mlab.mesh(x, y, z)
mlab.show()


17.0318457
17.0317981
